import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {
  BlockchainTypes,
  CrossmintEnvironment,
  CrossmintEVMWalletAdapter,
} from "@crossmint/connect";

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [address, setAddress] = useState<string | undefined>(undefined);

  async function connectToCrossmint() {
    // Initialize the Crossmint connect.
    const _crossmintConnect = new CrossmintEVMWalletAdapter({
      apiKey: process.env.NEXT_PUBLIC_CROSSMINT_API_KEY || 'yourApiKeyHere',
      chain: BlockchainTypes.ETHEREUM, // BlockchainTypes.ETHEREUM || BlockchainTypes.POLYGON. For solana use BlockchainTypes.SOLANA
    });

    // Ask the user to sign in and give access to their publicKey
    const address = await _crossmintConnect.connect();

    // If the user successfully connects to Crossmint, the address will be returned.
    if (address) {
      setAddress(address);
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>
            Crossmint wallet PoC
          </h1>
          <div>
            <button
              onClick={connectToCrossmint}
              className="px-6 py-2 font-semibold text-black bg-white rounded-md"
            >
              {address ? address.slice(0, 6) + "..." : "Connect"}
            </button>
          </div>
        </div>
      </main>
    </>
  )
}
